name: Pull Request another repository
description: Used for pull request a copy of a folder to another repository
inputs:
  source_folder:
    description: Source folder from origin
    required: true
  destination_repo:
    description: Destination repository
    required: true
  destination_folder:
    description: Destination folder to push the origin folder
    required: false
  user_email:
    description: Email for the git commit
    required: true
  user_name:
    description: GitHub username for the commit
    required: true
  destination_head_branch:
    description: The branch to create to push the changes. Cannot be master or main
    required: true
  destination_base_branch:
    description: The branch into which you want your code merged.
    required: false
    default: main
  pull_request_reviewers:
    description: Pull request reviewers users
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_folder }}
    - ${{ inputs.destination_repo }}
    - ${{ inputs.destination_folder }}
    - ${{ inputs.user_email }}
    - ${{ inputs.user_name }}
    - ${{ inputs.destination_head_branch }}
    - ${{ inputs.destination_base_branch }}
    - ${{ inputs.pull_request_reviewers }}
branding:
  icon: git-commit
  color: green
